blueprint:
  name: Notifications on doors/windows statuses
  description: Manage opened/closed entities when nobody is at home
  domain: automation
  source_url: https://github.com/francois09/HA_BP_misc/openings_notifications.yaml
  input:
    aperture_sensor:
      name: Door/Window aperture
      description: Room sensor for door or windows opening
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    person_location:
      name: Person location
      description: People location used to be at home
      selector:
        entity:
          domain: device_tracker
          multiple: true
    phone_device:
      name: Person device
      description: Device to use for notification
      selector:
        entity:
          domain: mobile_app
          multiple: true
    message_title:
      name: Title of the message
      description: Title used when sending the notification
      selector:
        text:
          type: text
    message_body:
      name: Body of the message
      description: Body used when sending the notification
      selector:
        text:
          type: text

mode: queued
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input aperture_sensor
  to: 'on'
- platform: zone
  entity_id: !input person_location
  zone: zone.home
  event: leave

condition:
- condition: zone
  entity_id: !input person_location
  zone: zone.home
  event: leave

action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input aperture_sensor
      state: 'on'
      match: any
    sequence:
    - service: notify.send_message
      data:
        message: !input message_body
        title: !input message_title
        entity_id: !input phone_device
