blueprint:
  name: Notifications on doors/windows statuses
  description: Manage opened/closed entities when nobody is at home
  domain: automation
  source_url: https://github.com/francois09/HA_BP_misc/openings_notifications.yaml
  input:
    aperture_sensor:
      name: Door/Window aperture
      description: Room sensor for door or windows opening
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    person_location:
      name: Person location
      description: People location used to be at home
      selector:
        entity:
          domain: device_tracker
          multiple: true
    phone_device:
      name: Person device
      description: People device to use for notification
      selector:
        entity:
          domain: device_tracker
          multiple: true

mode: queued
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input aperture_sensor
- platform: zone
  entity_id: !input person_location
  zone: zone.home
  event: leave

# condition:
#   - condition: state
#     entity_id: !input winter_mode_boolean
#     state: 'on'

action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input aperture_sensor
      state: 'on'
    sequence:
    - service: notify.send_message
      data:
        message: "a message"
        title: "a title"
        entity_id: !input phone_device
