blueprint:
  name: Notifications on doors/windows statuses
  description: Manage opened/closed entities when nobody is at home
  domain: automation
  source_url: https://github.com/francois09/HA_BP_misc/openings_notifications.yaml
  input:
    aperture_sensor:
      name: Door/Window aperture
      description: Room sensor for door or windows opening
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    person_location:
      name: Person location
      description: People location used to be at home
      selector:
        entity:
          domain: device_tracker
          multiple: false
    presence_mode_boolean:
      name: Presence info
      description: Indicates if there is somebody home
      selector:
        entity:
          domain: input_boolean
    notify_device:
      name: Device to notify
      description: Device to use for notification
      selector:
        device:
          filter:
            - integration: mobile_app
          multiple: false
    message_title:
      name: Title of the message
      description: Title used when sending the notification
      selector:
        text:
          type: text
    message_body:
      name: Body of the message
      description: Body used when sending the notification
      selector:
        text:
          type: text

mode: queued
max_exceeded: silent

trigger:
- platform: state
  entity_id: !input aperture_sensor
  to: 'on'
- platform: zone
  entity_id: !input person_location
  zone: zone.home
  event: leave
- platform: state
  entity_id: !input presence_mode_boolean

condition:
  - condition: and
    conditions:
    - condition: not
      conditions:
        - condition: zone
          entity_id: !input person_location
          zone: zone.home
    - condition: not
      conditions:
        - condition: state
          entity_id: !input presence_mode_boolean
          state: 'on'

action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input aperture_sensor
      state: 'on'
      match: any
    sequence:
      - domain: mobile_app
        type: notify
        message: !input message_body
        title: !input message_title
        device_id: !input notify_device
